language: cpp
dist: trusty
sudo: required

compiler:
    - clang
    - gcc

branches:
  only:
    - master
    - sp/travis

install:
    - travis_retry sudo apt-get -f install -y aptitude
    - travis_retry sudo aptitude -f install -y cmake
    - travis_retry sudo aptitude -f install -y mosquitto

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - travis_retry ./test/fastlib_communication_test -v
    - travis_retry ./test/fastlib_task_test -v

notifications:
  recipients:
    - spickartz@eonerc.rwth-aachen.de
    - tohliger@eonerc.rwth-aachen.de
  email:
    on_success: change
    on_failure: always

os:
  - linux
