branches:
  only:
    - master
    - sp/travis

before_install:
    - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - travis_retry sudo apt-get update -y

install:
    - travis_retry sudo apt-get -f install -y aptitude
    - travis_retry sudo aptitude -f install -y cmake
    - travis_retry sudo aptitude -f install -y gcc-4.8 g++-4.8
    - travis_retry sudo aptitude -f install -y mosquitto

    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - travis_retry ./examples/communication/fastlib_example_communication
    - travis_retry ./examples/comm_serial/fastlib_example_comm_serial 

notifications:
  recipients:
    - spickartz@eonerc.rwth-aachen.de 
    - tohliger@eonerc.rwth-aachen.de 
  email:
    on_success: change
    on_failure: always

os:
  - linux
